#%RAML 1.0 Library

usage: Collection of common annotations

annotationTypes:
  sandboxData:
  status:
    enum: [ PUBLISHED, PROTOTYPED, RETIRED ]
    required: true
  scopes:
    type: array
    items:
      type: object
      properties:
        key:
          required: true
        name:
          required: true
        description:
          required: true
  context:
  serviceUrl:
