#%RAML 1.0 Library

usage: Collection of common annotations

annotationTypes:
  config: object
  group:
    type: object
    properties:
      name: string
      description: string
  fieldOptionalityUnknown: nil
  sandboxData:
  deprecationMessage:
  documentation:
  status:
    enum: [ PUBLISHED, PROTOTYPED, RETIRED ]
    required: true
  scopes:
    type: array
    items:
      type: object
      properties:
        key:
          required: true
        name:
          required: true
        description:
          required: true
  scope:
    type: object
    properties:
      key:
        required: true
      name:
        required: true
      description:
        required: true
  context:
  serviceUrl:
