#%RAML 1.0
---

title: Calendar API
description: My Calendar API
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

(annotations.context): calendar
(annotations.serviceUrl): http://localhost:8080
(annotations.status): PUBLISHED
(annotations.scopes):
  -
    key: "read:calendar"
    name: "See calendar"

documentation:
 - title: Overview
   content: !include docs/overview.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: include/securitySchemes.raml
  headers: include/headers.raml
  annotations: include/annotations.raml

/calendar:
  /today:
    get:
      displayName: Get today's date
      description: This returns today
      is: [headers.acceptHeader]
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:calendar" ] } ]
      (annotations.sandboxData): !include docs/root.md
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:calendar scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      responses:
        200:
          description: Today's date
          body:
            application/json:
              example: !include docs/examples/root.json
              type: !include docs/examples/schema.json
